### PR TITLE
Recall with an uppercase, otherwise Recall does not work on  a case sensitive operating system.

### PR DESCRIPTION
**Pull request by EwenG**

### CODE REVIEW

**Comment by joshuafcole** [comment]
Hey Ewen, this is definitely an issue, but we're going to need to also support lower case for users that have cloned the repository manually. The simplest path would be to try requiring Recall, and if it doesn't exist, then try recall. You can accomplish that either with try...except or ltrap.ignore.

**Comment by EwenG** [comment]
I updated recall.js to support both upper and lower case directory name

**Comment by joshuafcole** [comment]
Great work, thanks!

**Comment by joshuafcole** [comment]
0.0.5 has been released, thanks.

**Pull request merged**
